name: Java CI
 
on: [push]
 
      uses: actions/checkout@v2
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
 
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
 
    - name: List files in the directory
      run: ls -la
 
    - name: Compile Java program 
      run: javac  test.java
 
    - name: Run Java program
      run: java test
